import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="bg-zinc-950">
        <div className="noise" />
        
        <div
          className="
          fixed
          inset-0
          -z-10
          opacity-20
          "
        >
          <div
            className="
            absolute
            top-0
            left-0
            h-125
            w-125
            rounded-full
            blur-3xl
          bg-cyan-500
            "
          />

          <div
            className="
            absolute
            bottom-0
            right-0
            h-125
            w-125
            rounded-full
            blur-3xl
          bg-purple-500
            "
          />
        </div>
        
        {children}
      </body>
    
    </html>
  );
}

